### ISSUE TITLE
Orebfuscator obfuscating chunks for Citizens NPC's

### ISSUE THREAD

**Issue by astr1al** [lishid/Orebfuscator#125]
My server seems to lag more over time, and is scheduled to restart every 24 hours. After some help from Spigot IRC evaluating a heap dump, they were able to determine that orebfuscator is trying to hide ores from NPC's from the Citizens plugin. https://cl.ly/3F2G3S3q1x40

This is on build 4.1.4 on spigot 1.10.2

**Comment by astr1al** [comment]
Here is a link to a heapdump. https://drive.google.com/open?id=0B4gbLqv0tkrNTWxCbzlUQkREb1U
Warning zip is 1.2 Gb and unzips to around 10 Gb

**Comment by RoboMWM** [comment]
Not sure how much can be done about this, since NPCs are very much like real players according to other plugins.

**Comment by astr1al** [comment]
That's what I was thinking, but don't see any ways to assign permissions to NPCs.

**Comment by RoboMWM** [comment]
Considering they're more or less treated like players, there should be a way to. I'd ask the Citizens devs. I don't see why not.

**Comment by mcmonkey4eva** [comment]
need to check `hasMetadata("npc")` on the entity before calculating random stuff for it.

**Comment by Morphan1** [comment]
Example:
```
    public static boolean isNPC(Entity entity) {
        return entity != null && entity.hasMetadata("NPC") && entity.getMetadata("NPC").get(0).asBoolean();
    }
```

**Comment by Aleksey-Terzi** [comment]
@mcmonkey4eva

Not sure this will be correct solution.
Today this will be Citizens plugin, tomorrow another plugin and we always should make sure Orebfuscator is working in some specific behavior with each custom plugin?  

Why just not use standard Bukkit's method as suggested RoboMWM, i.e. via permissions?
Orebfuscator is disabling obfuscation if player has permission **Orebfuscator.deobfuscate**.

So all you need is to ask Citizens' author about how to set permissions for NPC.

If Citizens plugin doesn't allow this and author is not willing to introduce this feature - I could introduce event into Orebfuscator which would allow to stop obfuscation for NPC from custom plugins.
And you can create your own small plugin to fix this in such way as you want.

**Comment by BlackCoyote** [comment]
@Aleksey-Terzi Hi! `entity.hasMetadata("NPC")` is already a fairly standardized method used in various popular plugins including worldguard. For example: [https://github.com/sk89q/WorldGuard/blob/12fc1438c2deeb081669c7e2ebdb1860a9337c24/worldguard-legacy/src/main/java/com/sk89q/worldguard/bukkit/util/Entities.java#L169](url)

**Comment by Aleksey-Terzi** [comment]
@BlackCoyote
Reasonable point.    
Thanks for comment.  
I will investigate this better and looks like actually will add support for NPC tag.

**Comment by mcmonkey4eva** [comment]
BTW, `So all you need is to ask Citizens' author about how to set permissions for NPC.`
This isn't actually possible. No perms plugins allow giving perms to NPCs, for some sad reason :(

Definitely best and easiest to add the NPC meta check (it's a no-dependencies basic Bukkit call too :D )

Thanks in advance for the fix!

**Comment by ProgrammerDan** [comment]
Would this technique also work for other NPC libraries such as https://github.com/InventivetalentDev/CompactNPCLib , or by adding explicit support for Citizens, would we open ourselves up to adding support for other libraries as well?

I agree that the solution for Citizens appears simple, but I disagree that this is the job of Orebfuscator.

Or, the middle road is -- instead of tying in to how a particular NPC library declares their NPCs, we recognize a particular Metadata tag _in general_ -- "Disable_Orebfuscation" -- which _anyone_ can set on their NPCs or specific players, in cases where permissions aren't available.

I might be arguing semantics but I don't really see a need to _in general_ disable Orebfuscator for NPCs. In some cases having it _on_ would be the correct behavior, and we shouldn't decide that for people who build NPCs; they should decide that for themselves, and we should merely provide a way for them to let us know.

**Comment by ProgrammerDan** [comment]
For example, if I wanted to create a "Miner NPC" -- I don't want him to have more knowledge then the players. Orebfuscator needs to be on and working for that NPC, otherwise players can use him to exploit a bypass around Orebfuscator -- just follow the bot around and dig the ores out in front of him.

**Comment by astr1al** [comment]
I'm not online to test but to me that's the same situation as a player standing next to an admin with deobfuscation permissions. The player should still see scrambled ores correct?

**Comment by ProgrammerDan** [comment]
My point is more central. Why are we deciding for everyone that NPCs should never have blocks obfuscated?

That's not our job.

Our job is to make it available, and to provide a way to turn it off, optionally.

We do that for players: we allow the use of a permission, and of blanket "off" for OPs.

We should add similar for NPCs; namely, the NPC creator can choose to tell us to disable Orebfuscation for all NPCs, or provide a similar thing to permission where _specific_ NPCs can have orebfuscation disabled.

This would be the more consistent solution, not implementing something specific to Citizens NPC implementation that shuts off Orebfuscator for all NPCs.

**Comment by RoboMWM** [comment]
In addition, while it's likely the hasMetadata check is inexpensive, I'd wonder if I could avoid having that check employed (if it is added) since I don't use NPCs.

**Comment by BlackCoyote** [comment]
@ProgrammerDan Generally speaking, It is never worth obfuscating ores for NPCS, since NPCS can't see them like that anyway. Your example of the player following the mining NPC is going to be an issue regardless of whether or not the NPC's ores are obfuscated as NPCS will read the world data directly on the server anyway. Any limitations the NPC would have, would have to be programmed in its own behaviour.

It's understandable you'd much rather want to work with a generalized meta tag rather than one for citizens specificly. However, Citizens, being the highest ranked NPC plugin at rank 9 of all tracked plugins, is setting the example for the "NPC" metadata to be this standard. A fair few plugins such as worldguard have adopted this as the standard method to detect if an entity is an NPC, making it the most common method for detecting NPCS already right now. Any NPC plugin that has not updated to this method is either one that is failing to stay up to date or has very stubborn developers! Besides that, it is simply more logical to, when you want an NPC to not mimic various player based scenarios, to just mark the entity as an NPC, rather than to mark that entity with all the behaviours you want to prevent it from triggering.

You suggested having ultimate control on a per NPC base by using permissions, and, though potentially pointless, that would have been an interesting feature to have, but as @mcmonkey4eva pointes out, adding permissions for NPCs would be extremely dificult if not impossible.

Ultimately, I genuinely do believe that, Orebfuscator, The definitive Anti X-Ray plugin for CraftBukkit, should only be obfuscating ores for those who can actually use X-Ray mods. and not NPCS who have serverside programming that would render orebfuscator's attempts to blur its vision useless. And since the metadata "NPC" is going to be the right method to detect if the entity is an NPC the vast majority of the time, it is going to be the best the way to accomplish that.
If you're truly concerned that in some scenarios, trying to obfuscate the vision for NPCS is a useful thing, we can always ask for it to be a configurable option in general.


Sorry for the long read, I hope you take the time to read through this! :)

**Comment by ProgrammerDan** [comment]
Fair point, @BlackCoyote, concerning direct world access.

I'm less convinced that Citizens being the leader means we should do what they do ;P.

None of my work with NPCs has involved Citizens because I wanted something _way_ more lightweight, like the NPC Library I linked to, which is well maintained but has very little cruft or lib depends -- a "developer's" NPC library, it's not very friendly to just Server Operators :).

So, my bias shows through.

So then, a proposal.

To address @RoboMWM 's concern, we could allow the check to be skipped (very agree).

To address @astr1al 's OP concern, we add a metadata check.

To address my concern, we make _which_ metadata field to check existence of, defined in config. with default as "NPC" to address @BlackCoyote 's reasoning that Citizens is the main NPC leader.

Proposed configuration options:

`NoObfuscationForMetadata`: false to disable the check, true to enable.

`NoObfuscationForMetadataTagName`: default to `NPC`, but leave definable.

Code change is direct and straightforward, lives alongside Op and Permission check, same pattern as well. Metadata Tag check will be existence only.

How's that sound @Aleksey-Terzi , @astr1al @RoboMWM @BlackCoyote and anyone else following along?

**Comment by BlackCoyote** [comment]
@ProgrammerDan To me, that sounds like it would do the job! (perhaps allow them to provide a list of metadata tag names instead of just one so it can work with multiple plugins with different metadatas at once!)

I'd also like to point out, @ProgrammerDan I did not mean my comment about citizens' popularity to come off like that, I simply meant with it that its popularity will have the 2 following effects:
- following its standard instead of another is percentually speaking going to solve the issue on the most servers at once!
- It creates an example status and credibility that convinces other plugins to either already have been adapted, or to be going to adapt to this method!

I definitely did not mean we should disregard smaller plugins their unique methods with that! (Though I'd hope for their sake they would adapt to the standardized method instead!)

**Comment by ProgrammerDan** [comment]
I thought about the list, but it seems unlikely that more then one NPC library will be co-resident, as they will likely trample on each other's toes when trying to manage their NPC's!  :)

Don't worry, no offense was taken about Citizen's popularity, quite the contrary -- it's a wonderful tool, and its popularity demonstrates that :). I just keep my eyes out for the little guy, when I can! Haha.

**Comment by mcmonkey4eva** [comment]
That seems like a reasonable solution. I'd add that `NoObfuscationForMetadata` should default to `true`.

**Comment by Aleksey-Terzi** [comment]
>  NoObfuscationForMetadata: false to disable the check, true to enable.
> NoObfuscationForMetadataTagName: default to NPC, but leave definable
> How's that sound @Aleksey-Terzi , @astr1al @RoboMWM @BlackCoyote and anyone else following along?

This sound excellent!

> I thought about the list, but it seems unlikely that more then one NPC library will be co-resident, as they will likely trample on each other's toes when trying to manage their NPC's! :)

Agree.

> That seems like a reasonable solution. I'd add that NoObfuscationForMetadata should default to true.

Agree.

**Comment by astr1al** [comment]
@Aleksey-Terzi completely onboard with the solution. Hopefully this helps ops all across the land. Monuments will be built commemerating the significant group efforts, women will name their children in your honour, and a new constellation added to the stars. This is quite a historical event.

**Comment by astr1al** [comment]
Eta on an update? My server has been running naked for two weeks, no-one has figured out anti xray is off but it's only a matter of time. Thanks :)

**Comment by ProgrammerDan** [comment]
Just waiting on me to bake a build, I'll aim to get that out tonight :). Thanks for patience!

**Comment by ProgrammerDan** [comment]
@astr1al  Release drop: https://github.com/lishid/Orebfuscator/releases/tag/4.1.8

I'll be pushing to BukkitDev and SpigotMC later on tonight.

**Comment by astr1al** [comment]
Awesome, just downloaded and testing now, I don't see an option for `NoObfuscationForMetadata` in the config anywhere. Did you decide to go a different route?

**Comment by ProgrammerDan** [comment]
https://github.com/DevotedMC/Orebfuscator/commit/9b6ce3679dd92d885a093bfd8581d7081b42b8e2#diff-dd663a6232a21358caad1c8f557cc036R453

Looks like we forgot to add example lines to the config!

However, that is the config line, as described.

**Comment by astr1al** [comment]
Alright no biggie, just so there's no confusion the config addition should look like this? `NoObfuscationForMetadata: true`

or is there a list config item like 

'  NoObfuscationForMetadata:
  - NPC'

**Comment by Aleksey-Terzi** [comment]
Default values will be added to config after server start.

It will add following lines:

Booleans:
...
NoObfuscationForMetadata: true

and

Strings:
...
NoObfuscationForMetadataTagName: NPC

Also config file is described in wiki: https://github.com/lishid/Orebfuscator/wiki/Configuration-File

Please let me know if problem solved.

**Comment by Aleksey-Terzi** [comment]
I'm supposing problem is solved therefore closing issue.

**Comment by astr1al** [comment]
Hello, I was just scanning my plugins for updates. I noticed the version I have since the fix is 4.1.8 but your development builds only list up to 4.1.4. Are there any recent updates since closing this? Thanks :)

**Comment by Aleksey-Terzi** [comment]
Hello,
Yes there are some different changes were done.
You can look details and get compiled plugin here: https://github.com/lishid/Orebfuscator/releases
There are two important changes - disabled ChunkReloader to increase performance and changed config to allow per-world settings for Orebfuscator.

**Comment by ProgrammerDan** [comment]
@astr1al I am woefully behind on bukkitdev and spigot releases, but I make every effort to keep the builds hosted here both stable and up to date -- 4.1.14 is latest.

**Comment by astr1al** [comment]
Ah! I didn't realize it was 4.1.14, not 4.1.1 :p Sorry for any confusion. Thanks for keeping this plugin going.
