### ISSUE TITLE
Farmland makes obfuscated blocks visible

### ISSUE THREAD

**Issue by bswartz** [lishid/Orebfuscator#139]
Because farmland is partially transparent (15/16 of a block high) it's possible to see the top of the block next to it. However orebfuscator doesn't seem to realize this and fails to update the exposed blocks to their correct values.

This is easy to reproduce. Dig down underground and create a room, then fill the lower layer with dirt, at add at least one water block. Disconnect to clear the client's memory of the blocks that were there. Log back in and turn the dirt to farmland with a hoe. You will see mossy cobblestone, obsidian, redstone, etc where there is only normal stone.

If you mine either the dirt next to the obfuscated block or the wall above it, the server send the correct block immediately. However under normal circumstances it just looks weird with a bunch of fake blocks exposed in your underground farm.

![2016-12-04_20 43 27](https://cloud.githubusercontent.com/assets/1328908/20871324/8e68ec80-ba62-11e6-8075-8ef3ba391b0d.png)

**Comment by ProgrammerDan** [comment]
This adds some weird exploits if we by default make farmland transparent, but it's a good catch. 

For server owners like yourself who don't like it, you can force Farmland to be a transparent block in the configuration -- check the TransparentBlocks explanation here: https://github.com/lishid/Orebfuscator/wiki/Configuration-File-(before-4.1.14) . I'll leave this open for Aleksey to comment if he thinks it should be a default transparent or not. 

In any case for your immediate need you can easily fix it in config.

**Comment by Aleksey-Terzi** [comment]
Since block transparency is configurable parameter, then question should it be non-transparent by default or transparent.

Some facts:

1. This issue is actual only for Engine Mode 2, because of Engine Mode 1 obfuscates STONE to STONE (by default, but this could be changed in config), but decoration blocks (like bricks, chiseled stone and etc) - it not obfuscate by default

2. In my opinion this is not usual behavior when people building farm in stone covered room. As from what I seen and did - usually this is either farm on the surface under the sky or room built from decoration blocks

3. We had similar issue with lava and it was solved by marking lava as transparent block by default and non-transparent for Engine Mode 1. But for lava this is different case because of lava in stone room is normal case.

Therefore I still think we should leave farmland as non-transparent for both engine modes by default.

If you don't like this behavior then you can add SOIL block to Lists.NonTransparentBlocks and it will be non-transparent.
