### ISSUE TITLE
Fake Ores

### ISSUE THREAD

**Issue by DKing328** [lishid/Orebfuscator#144]
False ores showing for players. Doesn't seem to be caused by lag on the server. 

Proof: https://www.youtube.com/watch?v=T6DMAeKUBMQ
Version: [23:10:03 INFO]: Orebfuscator4 version 4.2.0
Spigot Version: 1.11.2
Config: http://pastebin.com/qSA6SHsH

We've switched to EngineMode 1 for the time being to temporarily fix these issues. 
Any help is appreciated.

EDIT: Upon further inspection, seems to be related to the unnatural enchants that we allow players to use on the server. We run the plugin CrazyEnchantments, and it seems that when players use the enchantments from that plugin, Orebfuscator doesn't seem to agree with that. Any way to run EngineMode 2 and these enchantments at the same time?

**Comment by RoboMWM** [comment]
> We run the plugin CrazyEnchantments, and it seems that when players use the enchantments from that plugin, Orebfuscator doesn't seem to agree with that. 

That's entirely CrazyEnchantments issue. They need to either use the proper bukkit API or fire bukkit API events to let other plugins know what they're doing. This will also fix any other plugin incompatibility issues that CrazyEnchantments may cause.

**Comment by kicjow** [comment]
@RoboMWM I am the dev of CE but I am not sure why my plugin would do this. Could you maybe explain to me why it would.

**Comment by RoboMWM** [comment]
I have no idea what your plugin does, but if it's doing anything like this guy mentioned in https://github.com/lishid/Orebfuscator/issues/81, then that would be why you should a) fire events for such actions, or b) specifying the player breaking the block (instead of doing something like setting the block to air/changing the block). 

Generally the latter is preferred.

**Comment by Aleksey-Terzi** [comment]
@kicjow
As already was told by RoboMWM If you want so your plugin be compatible with other plugins - you should follow standard behavior of Minecraft.
If you don't want this - that's your decision.

But answer was addressed to @DKing328 - if problem is related to incompatibility of CrazyEnchantments with Orebfuscator because of CrazyEnchantments doesn't follow standard behavior - then I nothing can do.

If this is actually problem of non-standard behavior of CrazyEnchantments  - this is not problem of Orebfuscator, this is problem of CrazyEnchantments plugin, because of we cannot provide support for **all** custom plugins.
If @kicjow can't follow standard behavior but want to make his plugin compatible with Orebfuscator - I'm open to help.

@DKing328 could you please provide full folder of your server with plugins (minimal set required to reproduce problem) and map so I could run and test it?

**Comment by DKing328** [comment]
@Aleksey-Terzi My server contains quite a few custom jars and modified configuration files for nearly every plugin, along with some of our build team's work. I'm not sure if I'd feel comfortable sending a copy over. 

Luckily, you can reproduce the exact issue by running a server using Orebfuscator with the configuration I provided and installing CrazyEnchantments. If you put the enchantment named "Blast" on a pickaxe, you should run into the same issue you saw in the video. Here's a link to the plugin download for CrazyEnchantments: https://www.spigotmc.org/resources/crazy-enchantments-new-gkitz.16470/

**Comment by Aleksey-Terzi** [comment]
> My server contains quite a few custom jars and modified configuration files for nearly every plugin, along with some of our build team's work. I'm not sure if I'd feel comfortable sending a copy over.

Actually I don't need exact copy of your server.
Idea was that you are providing server or exact steps of how to reproduce problem so I'm not spending time on tries to reproduce but spending only on fixing bug.
This is open source project so everyone interested should participate in its improvement as they can :)

> Luckily, you can reproduce the exact issue by running a server using Orebfuscator with the configuration I provided and installing CrazyEnchantments.

Ok, thanks, I will follow your steps (later) and look if I will be able to reproduce problem.

**Comment by DKing328** [comment]
@Aleksey-Terzi Ah, sorry for that misunderstanding, haha. Looking forward to hearing about the tests (and hopefully a solution soon). :^)

**Comment by Aleksey-Terzi** [comment]
As was supposed by RoboMWM bug happened because of CrazyEnchantments is not calling break (or explode?) event when player is breaking blocks by Blast pickaxe (like normal pickaxe is doing).
Therefore Orebfuscator don't know that its time to send update to client.

Btw, Orebfuscator also has method BlockUpdate.updateByLocations (and I'm successfully using it in my another plugin) which allows to refresh state of specified areas on client's side if plugin's author don't want to use standard events but want compatibility with Orebfuscator.

Therefore unfortunately CrazyEnchantments is not compatible with Orebfuscator.
