### ISSUE TITLE
Memory leak causing server crash

### ISSUE THREAD

**Issue by Bezod** [lishid/Orebfuscator#148]
Here are 4 separate crash logs: https://pastebin.com/GeWQHcNn
Running latest version of orebfuscator.
System information can be found at the bottom of the pastebin.

**Comment by ProgrammerDan** [comment]
I see that dynmap is running with a large number of active and pending tiles during the crash. If you disable dynmap but leave everything else on, do you still get server crashes?

Also, do you know what other plugins you are running that might manipulate transmitted block data to the client, if any? I don't recognize many of the plugins running, not that that means much as I personally run a small-ish set :).

The exception at the bottom is a co-modification exception, which afaik shouldn't be caused by Orebfuscator as orebfuscator doesn't actually modify any block data.

@Aleksey-Terzi any thoughts on these traces?

**Comment by Bezod** [comment]
Thanks for the suggestion! I'll disable dynmap for a while and see how it goes. I'm not sure which plugin tries to modify data. My apologies if this issue isn't related to orebfuscator!

**Comment by Aleksey-Terzi** [comment]
@Bezod

Why did you decided that error happened because of memory leak?
From what I can see in log file - current server's memory usage is 2GB and allowed up to 5GB.
So even if we have somewhere here memory leak - I don't think it related to the crash.

From crash report I see this error "java.util.ConcurrentModificationException"
99% - it happened because of some plugin is going through chunk hash table at the time when server is changing it.
This could be because of some plugin is reading/changing chunk hash table (actually this could be using of any server's function which is using chunk map) in non-main  thread.
We had such issue a long time ago in Orebfuscator this is why I know what is this :)

Log is requiring serious investigations to "guess" what plugin caused this error.
But I don't see any problems related to Orebfuscator at the moments of crashes in the log.

**Comment by Bezod** [comment]
I was told over at spigot forums that orebfuscator was the issue and that I should report it here. Thanks for the help!

**Comment by ProgrammerDan** [comment]
Any chance you can link us that forum thread? I've noticed that the forum folks are often quick to blame Orebfuscator, when any more it's one of the least likely causes ...

**Comment by Bezod** [comment]
Sure thing! Here it is: https://www.spigotmc.org/threads/server-has-been-crashing-once-or-twice-per-day-can-someone-help-me-make-sense-of-these-crashes.231142/

**Comment by ProgrammerDan** [comment]
Thanks so much @Bezod, I'll post over there too and try to inspire some deeper critical thinking, if you haven't found a solution yet perhaps it's still achievable.
