### ISSUE TITLE
Disable Worlds doesen't work.

### ISSUE THREAD

**Issue by Tiippex** [lishid/Orebfuscator#164]
Hello,

i tried for hours to use OFC only for one world.

Im on
Spigot: 1.12
OFC: 4.3.0
ProtocolLib: 4.3.0 http://ci.dmulloy2.net/job/ProtocolLib/373/

So i tried to do it in that way: https://hastebin.com/vicugatevu.vbs
I try to enable OFC only for the world with the name "Farming".

I hope someone can help me.
Best greetings
Tiippex

**Comment by Aleksey-Terzi** [comment]
Hello,

Just now tested your config and not able to reproduce problem.

What I did:

1) Setup same environment as you described: only Spigot, ProtocolLib and OFC
2) Run server using default config for OFC
3) Connected to server and it is working as expected - worlds "world" and "world_nether" are obfuscated (works both usual obfuscating and ProximityHider)
4) Replaced config of OFC by config you provided by replaced "Farming" by "world_nether" and entered "ofc reload" in server console
5) Reconnected my client - "world" is non-obfuscated now (as expected) but "world_nether" is obfuscated (as expected)

Are you sure that world named exactly "Farming"?
Do you have other plugins? Is it possible to test without other plugins, but leave only OFC and ProtocolLib?

Also could you please:
1) Tell me what step did you do and what did you expect to see and what it did?
2) Could you please do exactly same steps as I did? I mean create new vanilla world and try my steps.

**Comment by Tiippex** [comment]
Ok i try it later.
Maybe one of these plugins causes the problem:
CoreProtect, SketchMap, ServerTutorialPlus, PlugMan, WorldBorder, ButtonCommands, BannerBoard, Votifier, **Multiverse-Core**, ProtocolLib, FastAsyncWorldEdit, BannerBoard_Skills, PermissionsEx, **EpicWorldGenerator**, TreeFeller, **Multiverse-Portals**, Vault, MessageFilter, **EpicNetherGenerator**, GernlernenSystem, Orebfuscator4, FastAsyncVoxelSniper, DabCore, **PerWorldInventory**, HeadDatabase, LWC, HolographicDisplays, UltimateFireworks, BannerMaker, Citizens, VoxelSniper, SignBoard, TotalTracker, Lottery, CommandNPC, Bank, WorldEdit, VisualWorldEdit, WorldGuard, ChestShop, ArmorStandEditor

I highlighted the plugins which do a lot of stuff with worlds etc.

**Comment by Tiippex** [comment]
Ok i disabled nearly everything:
![pluginlist](https://user-images.githubusercontent.com/16509128/28537438-c06e5d9a-70a2-11e7-8a4e-ccdbee0761cc.png)

Then i modified the config:
https://hastebin.com/pafovesabi.vbs

Thats a screenshot from Mutliverse WorldList:
![multiverse](https://user-images.githubusercontent.com/16509128/28537506-09588e36-70a3-11e7-849c-a54fcd480d7e.png)

As you can the, its activated for this world, but it doesent work, i set it to engine mode 1/2. Both doesent work. And i prefer 1.

Tiippex

**Comment by Aleksey-Terzi** [comment]
1. Did you try to run server with default config, Is OFC works at all?

2. Could you please enter command "ofc status" in server console and after that send me full server's log?

I think there maybe some exception or etc related to OFC.

**Comment by Tiippex** [comment]
Did you try to run server with default config, Is OFC works at all?
When i turn it on for every world, it works.

[16:35:31 INFO]: [OFC] Orebfuscator 4.3.0 is: Enabled
[16:35:31 INFO]: [OFC] Engine Mode: 1
[16:35:31 INFO]: [OFC] Caching: Enabled
[16:35:31 INFO]: [OFC] ProximityHider: Enabled
[16:35:31 INFO]: [OFC] DarknessHideBlocks: Disabled
[16:35:31 INFO]: [OFC] Initial Obfuscation Radius: 1
[16:35:31 INFO]: [OFC] Update Radius: 2
[16:35:31 INFO]: [OFC] Worlds: None
[16:35:31 INFO]: [OFC] Use worlds as: Whitelist

It says World: None
This is my actual config:  https://hastebin.com/otoboyevuv.vbs

My log, i think with only warns from HolographicDisplays: https://hastebin.com/agojihutaw.md

**Comment by Aleksey-Terzi** [comment]
> [16:35:31 INFO]: [OFC] Worlds: None

This is strange, because of it should show all worlds in any case, even if world is invalid.
Are you sure config you provided is the same as used on the server?

> My log, i think with only warns from HolographicDisplays: https://hastebin.com/agojihutaw.md

Hm, but it doesn't include messages from "ofc status"?

Is it possible for you to prepare some server folder I could put on my side, run server from it and test?
Until I could reproduce problem - I just don't know how to help.

**Comment by Tiippex** [comment]
I think I can't do that, to many premium plugins....
But do you have Discord/Teamspeak?
Than you can have a look over Teamviewer e.g.

Hm, but it doesn't include messages from "ofc status"?
Yeah I typed in just before I made the restart...

**Comment by Aleksey-Terzi** [comment]
> I think I can't do that, to many premium plugins....

Ok, but can you please just just leave required plugins and provide me folder?
I don't need full environment or live maps - I just need to reproduce problem so I could help you.

> But do you have Discord/Teamspeak?

I prefer to work in offline mode.

**Comment by Tiippex** [comment]
Is it possible to send PN via GitHub?

**Comment by Tiippex** [comment]
Any results?

I really would like to use this plugin.

Tiippex

**Comment by Matmorcat** [comment]
I'm having the same issue. I've tried blacklist and whitelist using the 4.3.0 format and regardless it still applies it to all worlds, even when it shows Whitelist mode with "Worlds: None" in /ofc status. When I do **/ofc reload** the values in OFC status turn to "Worlds: abraxusbuild," and "Use worlds as: Whitelist", but then it changes back to "Worlds: None" and "Use worlds as: Whitelist" after a few seconds.

Config.yml: https://gist.github.com/Matmorcat/40ed6595b9361ee1a4cd9f9c558e4289

Worlds I want enabled: Build & Abraxus
Worlds that should be disabled: Creative, Film, Nether, End, PvP, & Spawn

Plugins (45): CoreProtect, TerrainControl, OpenInv, PlaceholderAPI, PluginManagerReloaded, AdvancedBan, BuycraftX, Votifier, Multiverse-Core, ProtocolLib, NoCheatPlus, CustomPolls, VotingPlugin, FastAsyncWorldEdit, Multiverse-Inventories, DeluxeMenus, BlocksHub, PermissionsEx, LagMeter, Multiverse-Portals, Vault, PlayerHeads, MyWarp, VentureChat, Orebfuscator4, FastAsyncVoxelSniper, EpicRename, PwnFilter, LWC, SaneEconomy, ReportRTS, OnTime, DiscordSRV, VanishNoPacket, VoxelSniper, AncientGates, WorldEdit, CommandBook, WorldGuard, ChopTree3, ShopChest, MyPet, HomeSpawnPlus, PreciousStones, CF-Core

**Comment by Tiippex** [comment]
These are the plugins we both have:

CoreProtect, Votifier, Multiverse-Core, ProtocolLib, FastAsyncWorldEdit, PermissionsEx, Multiverse-Portals, Vault, Orebfuscator4, FastAsyncVoxelSniper, LWC, VoxelSniper, WorldEdit, WorldGuard

Nice to see someone who has exactly the same problem.

Tiippex

**Comment by Matmorcat** [comment]
It seems as though its a problem relating to load the config values for some reason or another, possibly because of the change in config. I had Orebfuscator for a long time before 4.3.0 and the old configuration worked for me. We just updated to 1.12 (been running ViaVersion up until now) and needed to update, so I removed all the Orebfuscator data and cache and let it generate new files. The Using the /ofc <enable/disable> <world> or /ofc use <whitelist/blacklist> don't seem to work, just pull up the help menu, assuming I'm using them right:
/ofc enable Build
/ofc use whitelist

neither of these work

**Comment by Matmorcat** [comment]
Another thing I notice is that our worlds both have capitals in the names, which I know sometimes might cause problems

**Comment by Aleksey-Terzi** [comment]
I propose the following - could someone please do the following:

1) Determine minimal conditions/configuration of server required to reproduce problem. As Matmorcat mentioned - problem could be somehow related to capital letters in world names

2) Create clean server folder with clean world maps, make sure problem still could be reproduced here

3) Either describe step by step what U have to do do create exactly same server or just provide me folder of this server

After that - I will take these steps or folder, if there will be some other plugins excluding ProtocolLib and Orebf - I will download their official versions and setup my local server and will try to reproduce problem.

If problem will be related to Orebfuscator but not bug in other plugins - I will make fix.
I think something actually could be wrong in Orebfuscator, because of even if world doesn't exist - it anyway should be in the list.
Orebf is loading world config on server start, but first activation of world configuration will be done only when world with this name/type is demanded (i.e. lazy initialization)

I will be happy to fix bug and help the problem, but I need to know how to reproduce this issue.

**Comment by Aleksey-Terzi** [comment]
@Tiippex sorry - I didn't mention you actually uploaded plugins.
Thanks for this.

I tested and - it is still ok for default server settings.

What I did:

1) Created empty folder
2) Put here spigot and put here plugins you provided
3) Run server - it works ok
4) Then copy-pasted your config file - and tried status - "farming" word is here:

![image](https://user-images.githubusercontent.com/5383652/28815517-4b04796e-76aa-11e7-8bdf-d7c11a838f34.png)

(name is lower-cased because of world manager is using lower-cased keys for hash table, i.e. it is case-insensitive)

Therefore I think something wrong with settings.

Could you please provide info I asked in my post above?

**Comment by Aleksey-Terzi** [comment]
Oh, I think I reproduced problem.
I will let you know when it will be fixed.

**Comment by Tiippex** [comment]
Thanks nice, how did you reproduced the problem?

**Comment by Aleksey-Terzi** [comment]
Bug is fixed.
Problem was related to bug in OFC and could be reproduced by using capitalized letters in world name and then full restart of MC.

You can use either my jar: https://www.dropbox.com/s/nxmepxhliper6kv/orebfuscator-4.3.2-SNAPSHOT.jar?dl=0
Or you can compile it from sources on DevotedMC fork.
Or you can wait for official release (I'm supposing Dan will make it soon)

Please reopen issue if you still have problems.

**Comment by Matmorcat** [comment]
Using the jar you linked, I cleared the cache and restarted the server. In/ ofc status, the correct worlds show in the list and "World by Default: Disabled", but all of our worlds are still being obfuscated and files are still being generated in the cache folder for every world that players teleport to, regardless of of the whitelist.

**Comment by Tiippex** [comment]
I agree with @Matmorcat

**Comment by Aleksey-Terzi** [comment]
@Matmorcat In my test it work for vanilla world with only 2 plugins ProtocolLib and Orebfuscator.
There is my config: https://pastebin.com/FfGaSsBf

Could you please provide me exact steps of what I should to do to create test server and see problem?

**Comment by Matmorcat** [comment]
I tried your config and just changed the worlds under EnabledWorlds and the engine type and it seems to work now! Though the cache still generates files for every world.

**Comment by Tiippex** [comment]
Sorry it worked for me, I was wrong.
I used the wrong engine mode and I was not looking enough with xray to see the difference....

**Comment by Aleksey-Terzi** [comment]
Thanks for your both feedback.
About cache files - I will look into the problem and will try to fix.
