### ISSUE TITLE
Spigot dropped the built-in anti xray system, the community needs an alternative!

### ISSUE THREAD

**Issue by sgdc3** [lishid/Orebfuscator#58]
@lishid

**Comment by HunterGPlays** [comment]
I don't think he keeps up with Minecraft anymore @sgdc3. Your best bet is to tag @MarioG1.

**Comment by sgdc3** [comment]
Thank you ;)

**Comment by lishid** [comment]
Yeah... I haven't been in the loop for quite a few years already. Haven't found anyone too willing to take over maintenance of the project though.

**Comment by lishid** [comment]
👍 I understand.

As I heard from md_5, MC1.9 introduced some new kind of chunk format that would make obfuscation extremely inefficient. His exact words were:

> Anti-xray has been removed. The technical reason for this is that we do not see a way to implement it without considerable performance overhead in the event that the addition of obfuscated blocks (especially in mode 2) requires a larger, resized, or different data palette. If someone is able to creatively overcome these issues with minimal performance impact, it may be restored.

I'm not sure what difficulty this means, but it's certain that it won't be as simple as refactoring and plugging the code in directly.

**Comment by MarioG1** [comment]
Yeah this is a problem.....

**Comment by ssamjh** [comment]
Any update on this?

**Comment by MarioG1** [comment]
They have made lots of internal changes in 1.9 and It is really difficult to update OFC to 1.9.
I don't want to spend lots of time updating this plugin since I don't play minecraft anymore and also don't own a server anymore.....
Sry.

**Comment by rErEaT** [comment]
sure we need something against xray :S

**Comment by ProgrammerDan** [comment]
@lishid We (and by we, I mean the amazing @Aleksei_Terzi ) have been hard at work updating Orebfuscator for 1.9.x and we have a working version now in testing on Devoted. 

Since neither you nor @MarioG1 have interest in continuing to support Orebfuscator, would you be interested in transferring management of the [curse](http://mods.curse.com/bukkit-plugins/minecraft/orebfuscator) and [http://dev.bukkit.org/bukkit-plugins/orebfuscator/](bukkit) pages to the group that Aleksei works with (DevotedMC)? 

Alternatively, do you have any objection if we open a _new_ Spigot/Bukkit/Curse set of pages under the label "Orebfuscator4"?

Our current progress in pre-release is here: https://github.com/DevotedMC/Orebfuscator and you can play-test it here: play.devotedmc.com:25568 or on our main server play.devotedmc.com as of this morning.

Thanks for the consideration.

**Comment by lishid** [comment]
So I added DevotedMC to the author on BukkitDev, but I'm not sure what to do for Curse.

**Comment by ProgrammerDan** [comment]
Thank you! The BukkitDev add came through fine. I'm also not yet entirely sure what to suggest with Curse either; I see DevotedMC is listed now under the project, we'll poke around a bit and see what the best action is there (if anything is possible).

**Comment by lishid** [comment]
I can also give DevotedMC access to my Orebfuscator repo.

**Comment by lishid** [comment]
Hmm, seems like DevotedMC is an organization and Github doesn't let me give access to an org. Can I just add some individual commiters?

**Comment by ProgrammerDan** [comment]
Thanks! Just add myself and @Aleksey-Terzi -- we're the senior-most devs in the org.

**Comment by lishid** [comment]
Done. Thanks for keeping this project going! It was really hard to find anyone willing and able to keep it alive.

**Comment by ProgrammerDan** [comment]
I believe it, this project represents an enormous effort and we're very grateful for the hard work of everyone involved! Thanks again. 

For everyone else watching this thread, watch for releases; I'll post them here as well as the DevotedMC repo and the BukkitDev/Curse sites.

**Comment by sgdc3** [comment]
Thank you ;)

**Comment by rErEaT** [comment]
How can we download it?

**Comment by ProgrammerDan** [comment]
@rErEaT There are a few "bigger" bugs yet that Aleks is working hard to squash. I'm doing another "live-test" on Devoted today, if it goes well I'll put up a pre-release.

**Comment by rErEaT** [comment]
@ProgrammerDan thanks, then waiting :)

**Comment by ProgrammerDan** [comment]
Okay folks, first alpha release is up here: https://github.com/lishid/Orebfuscator/releases/tag/v4.0.3-alpha

Please read carefully the known issues. Expect a second release tomorrow with the fix for "End" dimensions.

Tagging people who've replied to the thread:
@rErEaT @sgdc3 @ssamjh @HunterGPlays 

If you prefer to download from [BukkitDev](http://dev.bukkit.org/bukkit-plugins/orebfuscator/), the release should appear there later today, it's awaiting approval right now.

As always, please please open a new issue with any problems you encounter. 

Note that support for 1.8.x is unlikely to be continued; I've created a branch "v3.0.6" that I and Alex will gladly review pull requests against, but that's likely the limit of our consideration for 1.8.x moving forward.

**Comment by ProgrammerDan** [comment]
@lishid Can you alter the repository description to point to http://dev.bukkit.org/bukkit-plugins/orebfuscator/ instead of the legacy forum thread? It does not appear I can do so.

**Comment by lishid** [comment]
@ProgrammerDan Done. I also changed to description to match the one in the README file.

**Comment by ProgrammerDan** [comment]
Thank you very much. I'm going to close this issue now, thanks for everyone's contributions :)

**Comment by rErEaT** [comment]
nice work!

**Comment by EvilOlaf** [comment]
Awesome. Will give it a shot somewhen.
