### ISSUE TITLE
Blacklist as Whitelist

### ISSUE THREAD

**Issue by ProgrammerDan** [lishid/Orebfuscator#60]
Cross-posting relevant issues.

http://dev.bukkit.org/bukkit-plugins/orebfuscator/tickets/113-add-a-world-whitelist/

Likely would approach via the toggle idea. One list would perform both functions.

**Comment by Aleksey-Terzi** [comment]
Feature is implemented.

Now instead of **DisabledWorlds** list is used **Worlds** list.
If this whitelist or blacklist is determined by variable **UseWorldsAsBlacklist**.

New command is introduced: **ofc use whitelist | blacklist**
It allows to set value for UseWorldsAsBlacklist variable.

Old **DisabledWorlds** list automatically moved to **Worlds** list.

**Comment by ProgrammerDan** [comment]
Nice; is this active in 4.1.1 and updated in the wiki-documentation?

**Comment by Aleksey-Terzi** [comment]
> is this active in 4.1.1

No, this feature is available in 4.1.2.

> and updated in the wiki-documentation?

No, but I will update wiki at the end of the week.

**Comment by ProgrammerDan** [comment]
Perfect. Let me know if we need an early release.

**Comment by Aleksey-Terzi** [comment]
I propose to make new release as planned - at the end of week.
I'm planning to complete more issues for this new release.
