### ISSUE TITLE
Document UseSpecialBlockForProximityHider

### ISSUE THREAD

**Issue by RoboMWM** [lishid/Orebfuscator#71]
Unless this was in older builds (I've been using spigot antixray prior), the `UseSpecialBlockForProximityHider` seems to be new.

I'm unaware of any other new nodes introduced in version 4.

Thanks for the update by the way!

**Comment by ProgrammerDan** [comment]
I do believe it's been around for a while, but thanks! We'll get it documented shortly.

**Comment by Aleksey-Terzi** [comment]
> Unless this was in older builds (I've been using spigot antixray prior), the UseSpecialBlockForProximityHider seems to be new.

UseSpecialBlockForProximityHider is from 3.0.x builder, we didn't introduced any new nodes.
UseSpecialBlockForProximityHider - means that ProximityHider will use ProximityHiderID block fo obfuscation instead of standard mode 1 or mode 2 blocks.
This feature is especially useful if you are using mode 2 (default mode - random blocks), because of instead of chest you will see for example gold or diamond ore or other random block.
But when UseSpecialBlockForProximityHider  = true it will always use ProximityHiderID block.

**Comment by ProgrammerDan** [comment]
@RoboMWM Also added it but I saw it was already here: https://github.com/lishid/Orebfuscator/wiki/Configuration-File

Hope that helps!

**Comment by RoboMWM** [comment]
Oh, I must've missed it when I looked at it. Sorry :/
