### ISSUE TITLE
Extraneous features (proximity hider, DarknessHidesBlocks) weren't working properly

### ISSUE THREAD

**Issue by RoboMWM** [lishid/Orebfuscator#72]
I know when I tried this out with 1.8.8 some months ago, things like proximityhider didn't work too well, and blocks in light level 0 caused issues for players seeing chests in nether bases.

I'm assuming `proximityhider` is somewhat expensive on CPU (either hooking in PlayerMoveEvent or scanning locations of players every so often), so I'm personally not interested in enabling that feature, but I'm unsure if there's a good way to go about `DarknessHideBlocks` without also checking for player proximity/movement...

Either way, I prefer focus on the features the spigot antixray had, so if you don't have time to look into this, that's alright. Thanks again for providing us an update for 1.9!

**Comment by ProgrammerDan** [comment]
I'm a little unclear what the ask is on this issue; basically just focus testing on these specific features? 

I use proximity hider on my server -- if you want to hop on our test server and see how it performs small-scale, please feel free. play.devotedmc.com:25568 (if it's down just let me know, I don't always leave the test server up) or main server play.devotedmc.com .

I know in 3.0.5-6 on Civcraft, we used Proximity hider extensively, to great success and without too much lag. There were definitely some oddities, however. I'll do some evaluation to see if those issues remain. 

Finally, I totally agree that in prior version, DarknessHideBlocks did not function well, and makes mining largely untenable, sadly. We'll look into it, once we're sure any critical bugs are addressed.

Thanks!

**Comment by Aleksey-Terzi** [comment]
> I know when I tried this out with 1.8.8 some months ago, things like proximityhider didn't work too well

What issues you experienced previously with proximity hider?
Now it is working ok in 4.0.5.  
Also comparing to 3.0.6 - 4.0.5 is additionally deobfuscating nearby blocks on login, teleport or world change (not only on player move)
    
> I'm assuming proximityhider is somewhat expensive on CPU  

If you are using default config I don't think you will see any problems.
But if you will add all ore types to the ProximityHiderBlocks list and have a lot of players then maybe you will have some lags, but I'm not sure since haven't stats for "all ore types" + "a  lot of players".

> either hooking in PlayerMoveEvent

In latest version this are PlayerJoinEvent, PlayerMoveEvent, PlayerChangedWorldEvent and PlayerTeleportEvent.
But these handlers only adding player to the list - this is extremely fast.

> scanning locations of players every so often

ProximityHider is not scanning locations directly.
How it works:
1. Before sending packet to the client - plugin is adding to our list "ProximityHider" blocks
2. PlayerMoveEvent and other events - adding player to the list so that ProximityHider could investigate if some blocks became visible
3. Separate thread is going through player and "ProximityHider" blocks and check if block became visible for player. Since blocks are stored in our array - we are not calling getBlock and therefore this operation is enough fast, though we are still planning to improve this function as well. Also "ProximityHider" blocks list is not large with default config.

> but I'm unsure if there's a good way to go about DarknessHideBlocks

All DarknessHideBlocks is doing - hiding blocks which are surrounded with 0 light blocks.
So as you supposed chest in the nether will be hidden.
Also this function will make problem for people who is using "max bright".

So my recommendation - try to use default config - it is working very nice and I'm sure you will not see lags.
But one more time - we haven't stats about using plugin on large server, therefore situation here could differs.

**Comment by RoboMWM** [comment]
> What issues you experienced previously with proximity hider?

Basically it'd always show chests as hidden until you clicked on them, as if the location check didn't work. I guess I could enable it and test it again...

> All DarknessHideBlocks is doing - hiding blocks which are surrounded with 0 light blocks.

And you should know that in the nether, you can see well at light level 0. Some players had chests in a nether base, and one chest kept getting hidden because of this feature, because it was in the corner of their storage room.

> I'm a little unclear what the ask is on this issue; basically just focus testing on these specific features? 

Kinda, since these were issues I remembering experiencing when I tried an earlier version in 1.8.8 on another server.

**Comment by Aleksey-Terzi** [comment]
> Basically it'd always show chests as hidden until you clicked on them, as if the location check didn't work.   
    
This is definitely fixed now.  
    
> And you should know that in the nether, you can see well at light level 0.  
    
Yes I know and I agree that DarknessHideBlocks  is doing here not very well.  
Btw, we have change request about possibility to specify separate configs per world, I think this should solve problem (DarknessHideBlocks   could be disabled for Nether).

**Comment by RoboMWM** [comment]
Eh, I also wonder about those who do mine in the dark (depending on monitor you can see okayish in light level 0 in overworld), but I don't need a complicated multi-world config. If you do that though, allowing the possibility to have one config to define all would be appreciated.

**Comment by Aleksey-Terzi** [comment]
> Eh, I also wonder about those who do mine in the dark (depending on monitor you can see okayish in light level 0 in overworld),

Also player could modify client's options.txt to make dark to be the same as day:
![image](https://cloud.githubusercontent.com/assets/5383652/14748954/6c262aa6-08c5-11e6-8830-2bcc4b9cf791.png)

This is why I recommend to try default config (DarknessHideBlocks  is disabled here) with 4.0.5 and look if it will be ok for you.

**Comment by RoboMWM** [comment]
Correct, I have the feature off as well as proximityhider - will enable proximityhider though and see how well that performs.

**Comment by ProgrammerDan** [comment]
I don't know how many players you support, but if your playerbase has concurrent > 25 or so we'd love if you would share timings data with us.

**Comment by RoboMWM** [comment]
Anyways I've seen on another server that uses proximity hider and it works fine (albeit it's a bit odd to see random stones suddenly turn into crafting tables and chests, especially when they're put in plain site).
